### ISSUE TITLE
Issue with combo can you help

### ISSUE THREAD

**Issue by dylan4200000** [Rune701/Netflix-Account-Checker#1]
Hi having issue using email:pass combo and getting this message when trying main.py 

C:\Users\Administrator\Desktop\Netflix-Account-Checker-main>python main.py
WARNING:root:Can not find chromedriver for currently installed chrome version.
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Netflix-Account-Checker-main\main.py", line 87, in <module>
    main()
  File "C:\Users\Administrator\Desktop\Netflix-Account-Checker-main\main.py", line 81, in main
    email, password = line.strip().split(":")
    ^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

this is with 61k combos thanks

**Comment by Rune701** [comment]
check your combolist there's a invalid line somewhere. for example. a invalid character or username:pass. or something that just breaks the program
